#!/bin/sh

if ! zig build check; then
    echo "building failed"
    exit 1
fi

if ! zig build test; then
    echo "tests failed"
    exit 1
fi

if ! zig fmt --check .; then
    echo "formatting failed"
    exit 1
fi