#!/bin/sh

if ! zig fmt --check .; then
    zig fmt */*.zig *.zig
    echo "formatting failed"
    exit 1
fi


zig build check &
CHECK_PID=$!
zig build -Deval=hce check &
HCE_CHECK_PID=$!
zig build test -- tests/reduced.epd &
TEST_PID=$!

STATUS=0

if ! wait "$CHECK_PID"; then
    echo "building failed"
    STATUS=1
fi

if ! wait "$HCE_CHECK_PID"; then
    echo "hce build failed"
    STATUS=1
fi

if ! wait "$TEST_PID"; then
    echo "tests failed"
    STATUS=1
fi

exit "$STATUS"

